//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/MovimentoJogador/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""820f9df4-1888-4eaa-aa25-8e83bd07e9a1"",
            ""actions"": [
                {
                    ""name"": ""Moviment"",
                    ""type"": ""Value"",
                    ""id"": ""8f137bbf-ac85-4aa8-94ca-31175a5c742d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""eb9b61c4-556c-4077-873e-4e83ab0e9927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""4dfb1b5a-76d6-4dc2-afde-349fde72cf2c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SairEsc"",
                    ""type"": ""Button"",
                    ""id"": ""13c1d63e-8e17-453d-b60d-d607cc39fb39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feiticos1"",
                    ""type"": ""Button"",
                    ""id"": ""c34e9095-9e50-42da-9282-08f4f46adf06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feiticos2"",
                    ""type"": ""Button"",
                    ""id"": ""be781840-685a-428a-ac68-ad59111654bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feiticos3"",
                    ""type"": ""Button"",
                    ""id"": ""3af3c378-5c26-4483-91b7-9e9611813f40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feiticos4"",
                    ""type"": ""Button"",
                    ""id"": ""b68f1aa7-2e9b-4601-ad0d-b5e5923dbd0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feiticos5"",
                    ""type"": ""Button"",
                    ""id"": ""f17a296e-08e3-4e4a-b83c-6eee5afb90db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AtaqueNormal"",
                    ""type"": ""Button"",
                    ""id"": ""0a627ab8-e305-4b67-aadf-ee6f82c8dbf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""df5dbb91-b812-4654-a2ec-1fe672ecaced"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moviment"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0c47770e-be77-448b-920e-c494a700b857"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moviment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""62b73c57-00c9-4c4e-a69e-67e75a6319d0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moviment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1b4ac862-0602-4567-a207-93ccb9029ec6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moviment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e90c6840-e195-4347-8218-e69d7ad10149"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moviment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""252018a9-11d4-45ec-9751-aa2b22755615"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7e44272-f622-4a91-b979-7bfc6a462328"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d012e40-0bbb-4f1f-b9db-3854bc8e084d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SairEsc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ed93720-e7b2-4336-a5a7-16b112e34458"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feiticos1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a828d9cc-15b6-4fe5-8e9c-e960b47a7015"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feiticos2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0735455c-767d-4106-b9ed-c5f000ef2dbf"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feiticos3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2479e19e-89eb-4bee-975f-977638b429cf"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feiticos4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c9837b4-89bd-4cf1-902b-50dcd643bd2e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feiticos5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f82d18d4-e0b8-4218-930e-de192f68cc00"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AtaqueNormal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Moviment = m_Player.FindAction("Moviment", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_SairEsc = m_Player.FindAction("SairEsc", throwIfNotFound: true);
        m_Player_Feiticos1 = m_Player.FindAction("Feiticos1", throwIfNotFound: true);
        m_Player_Feiticos2 = m_Player.FindAction("Feiticos2", throwIfNotFound: true);
        m_Player_Feiticos3 = m_Player.FindAction("Feiticos3", throwIfNotFound: true);
        m_Player_Feiticos4 = m_Player.FindAction("Feiticos4", throwIfNotFound: true);
        m_Player_Feiticos5 = m_Player.FindAction("Feiticos5", throwIfNotFound: true);
        m_Player_AtaqueNormal = m_Player.FindAction("AtaqueNormal", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Moviment;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_SairEsc;
    private readonly InputAction m_Player_Feiticos1;
    private readonly InputAction m_Player_Feiticos2;
    private readonly InputAction m_Player_Feiticos3;
    private readonly InputAction m_Player_Feiticos4;
    private readonly InputAction m_Player_Feiticos5;
    private readonly InputAction m_Player_AtaqueNormal;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moviment => m_Wrapper.m_Player_Moviment;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @SairEsc => m_Wrapper.m_Player_SairEsc;
        public InputAction @Feiticos1 => m_Wrapper.m_Player_Feiticos1;
        public InputAction @Feiticos2 => m_Wrapper.m_Player_Feiticos2;
        public InputAction @Feiticos3 => m_Wrapper.m_Player_Feiticos3;
        public InputAction @Feiticos4 => m_Wrapper.m_Player_Feiticos4;
        public InputAction @Feiticos5 => m_Wrapper.m_Player_Feiticos5;
        public InputAction @AtaqueNormal => m_Wrapper.m_Player_AtaqueNormal;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Moviment.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoviment;
                @Moviment.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoviment;
                @Moviment.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoviment;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @SairEsc.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSairEsc;
                @SairEsc.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSairEsc;
                @SairEsc.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSairEsc;
                @Feiticos1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos1;
                @Feiticos1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos1;
                @Feiticos1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos1;
                @Feiticos2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos2;
                @Feiticos2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos2;
                @Feiticos2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos2;
                @Feiticos3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos3;
                @Feiticos3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos3;
                @Feiticos3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos3;
                @Feiticos4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos4;
                @Feiticos4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos4;
                @Feiticos4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos4;
                @Feiticos5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos5;
                @Feiticos5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos5;
                @Feiticos5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFeiticos5;
                @AtaqueNormal.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAtaqueNormal;
                @AtaqueNormal.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAtaqueNormal;
                @AtaqueNormal.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAtaqueNormal;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Moviment.started += instance.OnMoviment;
                @Moviment.performed += instance.OnMoviment;
                @Moviment.canceled += instance.OnMoviment;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @SairEsc.started += instance.OnSairEsc;
                @SairEsc.performed += instance.OnSairEsc;
                @SairEsc.canceled += instance.OnSairEsc;
                @Feiticos1.started += instance.OnFeiticos1;
                @Feiticos1.performed += instance.OnFeiticos1;
                @Feiticos1.canceled += instance.OnFeiticos1;
                @Feiticos2.started += instance.OnFeiticos2;
                @Feiticos2.performed += instance.OnFeiticos2;
                @Feiticos2.canceled += instance.OnFeiticos2;
                @Feiticos3.started += instance.OnFeiticos3;
                @Feiticos3.performed += instance.OnFeiticos3;
                @Feiticos3.canceled += instance.OnFeiticos3;
                @Feiticos4.started += instance.OnFeiticos4;
                @Feiticos4.performed += instance.OnFeiticos4;
                @Feiticos4.canceled += instance.OnFeiticos4;
                @Feiticos5.started += instance.OnFeiticos5;
                @Feiticos5.performed += instance.OnFeiticos5;
                @Feiticos5.canceled += instance.OnFeiticos5;
                @AtaqueNormal.started += instance.OnAtaqueNormal;
                @AtaqueNormal.performed += instance.OnAtaqueNormal;
                @AtaqueNormal.canceled += instance.OnAtaqueNormal;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMoviment(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSairEsc(InputAction.CallbackContext context);
        void OnFeiticos1(InputAction.CallbackContext context);
        void OnFeiticos2(InputAction.CallbackContext context);
        void OnFeiticos3(InputAction.CallbackContext context);
        void OnFeiticos4(InputAction.CallbackContext context);
        void OnFeiticos5(InputAction.CallbackContext context);
        void OnAtaqueNormal(InputAction.CallbackContext context);
    }
}
